apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-counter
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/your-username/simple-counter.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true